# Generated by Django 3.0.4 on 2022-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221129_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(default='Menu Option Available', max_length=250),
        ),
    ]
